name: eBPF_proc_image

on:
  push:
    branches:
      - "*"
    paths: 
      - 'eBPF_Supermarket/eBPF_proc_image/**'
      - '.github/workflows/eBPF_proc_image.yml'
  pull_request:
    branches:
      - "*"
    paths:
      - 'eBPF_Supermarket/eBPF_proc_image/**'
      - '.github/workflows/eBPF_proc_image.yml'

jobs:
  proc_image-project-build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Run lifecycle_image
        run: |
          cd eBPF_Supermarket/eBPF_proc_image
          sudo make lifecycle
          sudo ./lifecycle -t 1

      - name: Run proc_offcpu_time
        run: |
          cd eBPF_Supermarket/eBPF_proc_image/proc_offcpu_time
          sudo make
          sudo ./proc_offcpu_time -t 1

      - name: Run mutex_image
        run: |
          cd eBPF_Supermarket/eBPF_proc_image
          sudo make mutex_image
          sudo ./mutex_image -t 1

      - name: Run mutex_test1
        run: |
          cd eBPF_Supermarket/eBPF_proc_image/test
          sudo make
          sudo insmod mutex_test1.ko
          sudo insmod mutex_test2.ko
