name: fast_fuse

on:
  push:
    branches:
      - "*"
    paths: 
      - 'eBPF_Supermarket/Filesystem_Subsystem/fast_fuse/**'
      - '.github/workflows/fast_fuse.yml'
  pull_request:
    branches:
      - "*"
    paths:
      - 'eBPF_Supermarket/Filesystem_Subsystem/fast_fuse/**'
      - '.github/workflows/ebpf_FUSE_read.yml'
  
jobs:
  fast_fuse-build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      
      - name: Run fusedemo
        run: |
          cd eBPF_Supermarket/Filesystem_Subsystem/fast_fuse/fusedemo/
          sudo apt update
          sudo apt install fuse libfuse-dev meson wget git
          wget https://github.com/libfuse/libfuse/releases/download/fuse-3.16.2/fuse-3.16.2.tar.gz
          mkdir libfuse
          tar -zxvf fuse-3.16.2.tar.gz -C ./libfuse/
          cd libfuse
          cp ../fusedemo.c ./example/
          cp ../make.sh ./
          bash make.sh
          cd ./example/
          mkdir ./yourdir
          ./fusedemo ./yourdir
          df -T ./yourdir

      - name: Run frida
        run: |
          pip install frida-tools
          cd eBPF_Supermarket/Filesystem_Subsystem/fast_fuse/frida
          sudo sysctl kernel.yama.ptrace_scope=0
          python cat.py
