on:
  push:
    paths:
      - 'eBPF_Supermarket/Network_Subsystem/tcp_watch/**'
      - '.github/workflows/network_monitor.yml'
  pull_request:
    paths:
      - 'eBPF_Supermarket/eBPF_TCP_Ping/**'
      - '.github/workflows/network_monitor.yml'

jobs:
  run-test:
    name: Build and run
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y bison build-essential flex curl libedit-dev \
          libllvm12 llvm-12-dev libclang-12-dev python python3 python3-distutils zlib1g-dev libelf-dev libfl-dev \
          bpfcc-tools linux-headers-$(uname -r) libelf-dev libpcap-dev gcc-multilib build-essential
        sudo ln -sf /usr/bin/llc-12 /usr/bin/llc

    - name: Test Make
      run: |
        cd eBPF_Supermarket/Network_Subsystem/tcp_watch/
        make

    - name: Test run
      run: |
        cd eBPF_Supermarket/Network_Subsystem/tcp_watch/
        # run
        sudo timeout -s SIGINT 20 ./tcpwatch
